# Generated by Django 6.0 on 2026-02-23 22:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(choices=[('NIS2_DIRECTIVE', 'NIS2 Directive (Official)'), ('CYBERBEVEILIGINGSWET', 'Dutch Cyberbeveiligingswet'), ('NCSC_FACTSHEET', 'NCSC-NL Factsheet'), ('ISO_27001', 'ISO 27001 Mapping'), ('ENISA_GUIDELINE', 'ENISA Guideline'), ('INTERNAL', 'Internal Knowledge')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], max_length=2)),
                ('url', models.URLField(blank=True, help_text='Source URL if available')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_base/')),
                ('ingested', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('chunks_created', models.IntegerField(default=0)),
                ('qdrant_collection', models.CharField(default='nis2_knowledge_base', max_length=100)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('authority_level', models.IntegerField(default=5, help_text='1-10, higher = more authoritative')),
                ('times_retrieved', models.IntegerField(default=0)),
                ('last_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'ordering': ['-authority_level', 'source', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('kvk_number', models.CharField(help_text='Dutch KVK number', max_length=8, unique=True)),
                ('sector', models.CharField(choices=[('MSP', 'Managed Service Provider'), ('HOSTING', 'Hosting Provider'), ('CLOUD', 'Cloud Service Provider'), ('TRANSPORT', 'Digital Transport'), ('ENERGY', 'Energy Sector'), ('HEALTHCARE', 'Healthcare IT'), ('FINANCE', 'Financial Services'), ('TELECOM', 'Telecommunications'), ('OTHER', 'Other Essential Service')], max_length=20)),
                ('company_size', models.CharField(choices=[('SMALL', '10-49 employees'), ('MEDIUM', '50-249 employees'), ('LARGE', '250+ employees')], max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('T1', 'Tier 1 - Gap Analysis (€950)'), ('T2', 'Tier 2 - Implementation Docs (€2,500)'), ('T3', 'Tier 3 - Full Package (€5,000)')], max_length=2)),
                ('status', models.CharField(choices=[('INTAKE', 'Document Intake'), ('PROCESSING', 'AI Processing'), ('ANALYSIS', 'Gap Analysis'), ('REVIEW', 'Human Review'), ('COMPLETE', 'Completed'), ('DELIVERED', 'Delivered to Client')], default='INTAKE', max_length=20)),
                ('documents_uploaded', models.IntegerField(default=0)),
                ('total_pages_processed', models.IntegerField(default=0)),
                ('gaps_identified', models.IntegerField(default=0)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100% compliance score', max_digits=5, null=True)),
                ('report_generated', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal consultant notes')),
                ('client_feedback', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance_engine.client')),
            ],
            options={
                'verbose_name': 'Compliance Audit',
                'verbose_name_plural': 'Compliance Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('POLICY', 'Security Policy'), ('PROCEDURE', 'Security Procedure'), ('NETWORK_DIAGRAM', 'Network Diagram'), ('INCIDENT_PLAN', 'Incident Response Plan'), ('BCP', 'Business Continuity Plan'), ('RISK_ASSESSMENT', 'Risk Assessment'), ('AUDIT_REPORT', 'Previous Audit Report'), ('CERTIFICATE', 'Security Certificate'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='client_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('pages_count', models.IntegerField(blank=True, null=True)),
                ('text_extracted', models.BooleanField(default=False)),
                ('virus_scanned', models.BooleanField(default=False)),
                ('virus_found', models.BooleanField(default=False)),
                ('pii_detected', models.BooleanField(default=False)),
                ('pii_anonymized', models.BooleanField(default=False)),
                ('language_detected', models.CharField(blank=True, max_length=10)),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='AI-detected topics')),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 relevance to NIS2', max_digits=5, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance_engine.complianceaudit')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Controls'), ('ORGANIZATIONAL', 'Organizational Measures'), ('INCIDENT_RESPONSE', 'Incident Response'), ('SUPPLY_CHAIN', 'Supply Chain Security'), ('ENCRYPTION', 'Encryption & Cryptography'), ('ACCESS_CONTROL', 'Access Control'), ('LOGGING', 'Logging & Monitoring'), ('TRAINING', 'Security Awareness Training'), ('GOVERNANCE', 'Governance & Risk Management'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical - Immediate Action Required'), ('HIGH', 'High - Must Address Before Certification'), ('MEDIUM', 'Medium - Should Address'), ('LOW', 'Low - Nice to Have')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What is missing or non-compliant')),
                ('nis2_article', models.CharField(help_text='e.g., Article 21.2', max_length=50)),
                ('nis2_requirement', models.TextField(help_text='The actual NIS2 requirement text')),
                ('current_state', models.TextField(help_text='What the client currently has')),
                ('required_state', models.TextField(help_text='What NIS2 requires')),
                ('recommendation', models.TextField(help_text='How to fix this gap')),
                ('estimated_effort_hours', models.IntegerField(help_text='Estimated hours to implement')),
                ('estimated_cost_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_score', models.IntegerField(default=5, help_text='1-10 risk score')),
                ('business_impact', models.TextField(blank=True, help_text='Impact if not addressed')),
                ('addressed', models.BooleanField(default=False)),
                ('addressed_date', models.DateField(blank=True, null=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='compliance_engine.complianceaudit')),
            ],
            options={
                'verbose_name': 'Compliance Gap',
                'verbose_name_plural': 'Compliance Gaps',
                'ordering': ['-severity', '-risk_score', 'category'],
            },
        ),
    ]
