# Generated by Django 6.0 on 2026-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('DE', 'Germany'), ('BE', 'Belgium'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('PL', 'Poland'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('AT', 'Austria'), ('IE', 'Ireland'), ('GB', 'United Kingdom'), ('OTHER', 'Other EU')], default='NL', max_length=10),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
